Migrate local configs to chezmoi

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,11 +1,11 @@
 # If you come from bash you might have to change your $PATH.
-# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
+# export PATH=$HOME/bin:/usr/local/bin:$PATH
 
-# Path to your Oh My Zsh installation.
+# Path to your oh-my-zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
 
 # Set name of the theme to load --- if set to "random", it will
-# load a random theme each time Oh My Zsh is loaded, in which case,
+# load a random theme each time oh-my-zsh is loaded, in which case,
 # to know which specific one was loaded, run: echo $RANDOM_THEME
 # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
 ZSH_THEME=""
@@ -60,12 +60,12 @@ ZSH_THEME=""
 # "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
 # or set a custom format using the strftime function format specifications,
 # see 'man strftime' for details.
-# HIST_STAMPS="mm/dd/yyyy"
+HIST_STAMPS="yyyy-mm-dd"
 
 # Would you like to use another custom folder than $ZSH/custom?
 # ZSH_CUSTOM=/path/to/new-custom-folder
 
-export FZF_BASE=/usr/bin
+export FZF_BASE=/opt/homebrew/bin/fzf
 
 # Which plugins would you like to load?
 # Standard plugins can be found in $ZSH/plugins/
@@ -73,22 +73,33 @@ export FZF_BASE=/usr/bin
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
 plugins=(
-  bundler 
-  fzf 
-  git 
-  git-to-jj
-  jj
-  rails 
-  ruby
-  zoxide 
-  zsh-autosuggestions
-  zsh-syntax-highlighting
-  zsh-vi-mode
+    alias-finder
+    aliases
+    bundler
+    capistrano
+    docker-compose
+    fzf
+    fzf-alias
+    git
+    git-to-jj
+    jj
+    rails
+    ruby
+    ssh
+    starship
+    wd
+    zoxide
+    zsh-autosuggestions
+    zsh-syntax-highlighting
+    zsh-vim-mode
 )
 
 source $ZSH/oh-my-zsh.sh
 
 # User configuration
+
+# User bin directory
+export PATH="/Users/rfranke/bin:$PATH"
 
 # export MANPATH="/usr/local/man:$MANPATH"
 
@@ -99,27 +110,19 @@ source $ZSH/oh-my-zsh.sh
 # if [[ -n $SSH_CONNECTION ]]; then
 #   export EDITOR='vim'
 # else
-#   export EDITOR='nvim'
+#   export EDITOR='mvim'
 # fi
 
 # Compilation flags
-# export ARCHFLAGS="-arch $(uname -m)"
+# export ARCHFLAGS="-arch x86_64"
 
-# Set personal aliases, overriding those provided by Oh My Zsh libs,
-# plugins, and themes. Aliases can be placed here, though Oh My Zsh
-# users are encouraged to define aliases within a top-level file in
-# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
-# - $ZSH_CUSTOM/aliases.zsh
-# - $ZSH_CUSTOM/macos.zsh
+export GIT_PAGER="bat -p"
+
+# Set personal aliases, overriding those provided by oh-my-zsh libs,
+# plugins, and themes. Aliases can be placed here, though oh-my-zsh
+# users are encouraged to define aliases within the ZSH_CUSTOM folder.
 # For a full list of active aliases, run `alias`.
 #
-# Example aliases
-# alias zshconfig="mate ~/.zshrc"
-# alias ohmyzsh="mate ~/.oh-my-zsh"
-
-################################################################################
-# Aliases
-################################################################################
 # Aliases for eza
 alias ls='eza --icons'                                                          # ls
 alias l='eza -lbgF --time-style=long-iso --git --icons'                         # list, size, type, git
@@ -131,73 +134,139 @@ alias llx='eza -lbhHigUmuSa@ --time-style=long-iso --git --color-scale --icons' 
 
 # Use some modern tools instead of the original ones
 alias cat='bat'
-alias cd="z"
 alias vim="nvim"
 
-# Tools
-alias oc='opencode'
-alias ca='cursor-agent'
-alias lg='lazygit'
-alias d='docker'
-alias r='rails'
-n() { if [ "$#" -eq 0 ]; then nvim .; else nvim "$@"; fi; }
+# cd with zoxide fallback (Omarchy-style)
+if command -v zoxide &> /dev/null; then
+  zd() {
+    if (( $# == 0 )); then
+      builtin cd ~ || return
+    elif [[ -d $1 ]]; then
+      builtin cd "$1" || return
+    else
+      if ! z "$@"; then
+        echo "Error: Directory not found"
+        return 1
+      fi
 
-# Yazi
+      printf "\U000F17A9 "
+      pwd
+    fi
+  }
+  alias cd=zd
+  alias z=zd
+fi
+
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+
+# Other aliases
+alias lg="lazygit"
+alias zshconf="cursor ~/.zshrc"
+alias zshload="source ~/.zshrc"
+alias ohmyzsh="cursor ~/.oh-my-zsh"
+
+alias upgrade="brew update && brew upgrade && mas upgrade && mise upgrade"
+
+alias rbym="rubymine ."
+
+alias gbc="gitbatch -d ~/Workspace/Taktsoft/wlp.cloud"
+
+alias vagrant='sudo vagrant "$@"'
+
+alias devcup='devcontainer up --workspace-folder .'
+alias devcdn='docker compose -f .devcontainer/compose.yaml down'
+
+# >>> conda initialize >>>
+# !! Contents within this block are managed by 'conda init' !!
+# __conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
+# if [ $? -eq 0 ]; then
+#     eval "$__conda_setup"
+# else
+#     if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
+#         . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
+#     else
+#         export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
+#     fi
+# fi
+# unset __conda_setup
+# <<< conda initialize <<<
+
+# Define asdf related stuff
+export ASDF_GOLANG_MOD_VERSION_ENABLED=true
+
+# Fix arrows for history - See: https://github.com/ohmyzsh/ohmyzsh/issues/1720#issuecomment-286366959
+# start typing + [Up-Arrow] - fuzzy find history forward
+if [[ "${terminfo[kcuu1]}" != "" ]]; then
+  autoload -U up-line-or-beginning-search
+  zle -N up-line-or-beginning-search
+  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
+fi
+# start typing + [Down-Arrow] - fuzzy find history backward
+if [[ "${terminfo[kcud1]}" != "" ]]; then
+  autoload -U down-line-or-beginning-search
+  zle -N down-line-or-beginning-search
+  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
+fi
+
+# Initialize starship prompt
+# if [[ -n $WARP_SESSION_ID ]]; then
+#     export STARSHIP_CONFIG=~/.config/warp/starship.toml
+# fi
+# source <(/opt/homebrew/bin/starship init zsh --print-full-init)
+
 function y() {
 	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
-	command yazi "$@" --cwd-file="$tmp"
+	yazi "$@" --cwd-file="$tmp"
 	IFS= read -r -d '' cwd < "$tmp"
-	[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
+	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
 	rm -f -- "$tmp"
 }
 
-# Convenience
-open() {
-  xdg-open "$@" >/dev/null 2>&1 &
-}
+export PATH="/Users/rfranke/Workspace/tools/git-fuzzy/bin:$PATH"
 
-# Git
-alias glog='git log --pretty=format:"%C(yellow)%h%Creset %C(green)%ad%Creset %s %C(dim white)(%an <%ae>)%Creset" --date=short --decorate --graph'
-################################################################################
+export EDITOR="nvim"
 
-################################################################################
-# Additional environment variables
-################################################################################
-export PATH=./bin:~/.cargo/bin:$PATH
-################################################################################
+# export ITERM2_SQUELCH_MARK=1
+# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
 
-
-################################################################################
-# Initialize tools
-################################################################################
-if command -v mise &> /dev/null; then
-  eval "$(mise activate zsh)"
-fi
-
-if command -v starship &> /dev/null; then
-  eval "$(starship init zsh)"
-fi
-
-if command -v ~/.local/bin/cursor-agent %> /dev/null; then
-  eval "$(~/.local/bin/cursor-agent shell-integration zsh)"
-fi
-
-if command -v try &> /dev/null; then
-  eval "$(try init ~/Work/tries)"
-fi
-################################################################################
-
-################################################################################
-# Initialize fzf to work in combination with zsh-vi-mode
-################################################################################
-function zvm_after_init() {
+if [[ "$TERM_PROGRAM" == "iTerm.app" || "$TERM_PROGRAM" == "ghostty" ]]; then
   source <(fzf --zsh)
-}
-################################################################################
+fi
+# eval "$(tv init zsh)"
 
-################################################################################
-# 1password
-################################################################################
-export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
-source /home/rfranke/.config/op/plugins.sh
-################################################################################
+eval "$(mise activate zsh --shims)"
+
+# eval "$(zellij setup --generate-auto-start zsh)"
+
+autoload -U +X bashcompinit && bashcompinit
+complete -o nospace -C /opt/homebrew/bin/terraform terraform
+
+# Autoload zsh shell functions defined in the function path
+fpath=( ~/.zsh_autoload_functions "${fpath[@]}" )
+
+autoload -Uz load_gitlab_token
+
+export PATH="$HOME/.local/bin:$PATH"
+export PATH="$HOME/.cargo/bin:$PATH"
+
+source /Users/rfranke/.config/op/plugins.sh
+
+# Added by Antigravity
+export PATH="/Users/rfranke/.antigravity/antigravity/bin:$PATH"
+
+# The following lines have been added by Docker Desktop to enable Docker CLI completions.
+fpath=(/Users/rfranke/.docker/completions $fpath)
+autoload -Uz compinit
+compinit
+# End of Docker CLI completions
+
+# try - https://github.com/tobi/try
+eval "$(try init ~/Work/tries)"
+eval "$(atuin init zsh)"
+
+# Redmine CLI via 1Password
+redmine() {
+  op --env-file="${HOME}/.config/op/env.redmine" run -- redmine-cli "$@"
+}
